version: "3"
services:
  lru_cache:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: lru_cache-image
    container_name: lru_cache-container
    tty: true
